"""descripción del cambio

Revision ID: efdf3b7a88d0
Revises: bab884356185
Create Date: 2026-02-19 09:55:44.795699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdf3b7a88d0'
down_revision: Union[str, Sequence[str], None] = 'bab884356185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insult_comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'insult_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'insult_comments', 'insult_comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insult_comments', type_='foreignkey')
    op.drop_constraint(None, 'insult_comments', type_='foreignkey')
    op.drop_column('insult_comments', 'parent_id')
    # ### end Alembic commands ###
